name: Build

on:
    workflow_dispatch:
    push:
        branches: master

jobs:
    build:
        name: Build
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.8'
                cache: 'pip'
                cache-dependency-path: '**/requirements.txt'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Build
              run: pyinstaller -F -n Updater -i icon.ico update.py
            - name: Archive artifact
              uses: actions/upload-artifact@v4
              with:
                name: updater
                path: dist\Updater.exe

